packages:
  - apps/*
  - packages/*
catalog:
  next: ^15.4.6
  typescript: ^5.8.3
catalogs:
  react:
    react: 19.1.1
    react-dom: 19.1.1
    '@types/react': 19.1.8
    '@types/react-dom': 19.1.6
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js-pure
  - sharp
ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - prisma
